# name: Python app test with Github Actions

# # Controls when the workflow will run
# on:
#   push:
#     branches:
#       - Development
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.9
#       uses: actions/setup-python@v1
#       with:
#         python-version: 3.9
#     - name: Install dependencies
#       run: |
#         make install
#     - name: Lint with pylint
#       run: |
#         make lint
#     - name: Test with pytest
#       run: |
#         make test
#     - name: Format code
#       run: |
#         make format

runtime: python39
entrypoint: gunicorn -b 0.0.0.0:8080 main:server
